---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \usepackage{wrapfig}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf ASHLEE MARIE PEREZ}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}codebyashlee@gmail.com ∙ \href{https://www.linkedin.com/in/ashlee-perez/}{LinkedIn} ∙ \href{https://github.com/AshleeMPerez}{Github} ∙ \href{https://codebyashlee.shinyapps.io/shinyDash}{Portfolio}
\end{center}
\vspace{3pt}
\begin{center}{\bf Languages and Tools} - R/RStudio, RShiny, tidymodels, SAS/SPSS, STATA, SQL, Python, Tableau, AWS, BigQuery\end{center}


<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}
      \hspace{1 mm} {\bf Florida International University}\\
      \hspace{11 mm}Master's in Public Health: Biostatistics
    \end{flushleft}
    \begin{flushright}
    Miami, Florida
    \end{flushright}
  \end{multicols}
\end{large}


\vspace{0.05cm}

<!-- EDUCATION: 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}
      \hspace{1 mm} {\bf Florida International University}\\
      \hspace{11 mm}Bachelor of Arts: Pre-Veterinary Curriculum
    \end{flushleft}
    \begin{flushright}
    Miami, Florida
    \end{flushright}
  \end{multicols}
\end{large}
\vspace{5pt}

<!-- PERSONAL PROJECTS : 1ST BULLET -->
\begin{large}
{\bf SELECTED PROJECTS}
  \vspace{3pt}
  \hrule
    \begin{flushleft}\bf{Unveiling the Impact: The COVID-19 Pandemic and its Effect on Four Florida Counties}\end{flushleft}
  \vspace{-0.17cm}
\end{large}
* Automated import and processing of 386 CDC Community Profile Reports using  R/RStudio, *streamlining the calculation of COVID-19 outbreak metrics and improving reporting accuracy*. 
* Collaborated with colleagues to refine data collection methods, identifying trends through visualizations, and recommendations for public health initiatives.


\vspace{5pt}
\begin{large}
    \begin{flushleft}\bf{Association of Alcohol Consumption and Hours Worked in the United States (2017-2018)}\end{flushleft}
  \vspace{-0.17cm}
\end{large}
* Utilized *regression analysis and predictive modeling through R/RStudio* to examine possible association between alcohol consumption and hours worked from NHANES data (2017-2018), controlling for relevant demographic factors.
* Identified statistically significant associations, effectively communicated findings through clear and concise report, as well as oral presentation, *highlighting key insights and implications for policy and intervention strategies.*


\vspace{5pt}
\begin{large}
    \begin{flushleft}\bf{Head \& Neck and Thoracic Cancer Risk Amongst National Pre-COVID-19 Pandemic Survey Participants}\end{flushleft}
  \vspace{-0.17cm}
\end{large}
* Conducted an in-depth analysis to identify factors influencing cancer risk using multiple regression techniques prior to the COVID-19 pandemic with a focus on tobacco product consumption from NHANES 2017-2018.
* *Built and optimized multiple regression models to predict cancer risk based on selected variables using SAS/SPSS.*
Assessed statistical significance and interpretation to improve future preventative and diagnostic strategies.

\vspace{5pt}

<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}
      \bf \href{https://www.bayer.com/en/}{Bayer}\\
      Process Insights \& Analytics Intern
    \end{flushleft}
    \begin{flushright}
    May 2024 - Present\\
    \begin{small}Remote\end{small}
    \end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Collected and manipulated multiple genome sequencing data sets (over 900,000 rows) from BigQuery schemas, utilizing R/RStudio to develop summary files of pertinent dates, KPIs, and project details.
* **Designed novel product solutions to measure genome sequencing workflows and deployed interactive KPI dashboards and applications through RShiny. Deployed product through AWS and Posit Connect, enhancing accessibility and data-driven metrics for multiple teams.**
* Collaborated with cross functional teams, including lead researchers, laboratory technicians, and data scientists, to present data pipeline, product solutions, and application/dashboard demonstrations, as well as future feature integration.


\vspace{5pt}

<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}
      \bf \href{https://www.floridahealth.gov/}{Florida Department of Health}\\
      Applied Epidemiology Intern
    \end{flushleft}
    \begin{flushright}
    Jan 2024 - May 2024\\
    \begin{small}Miami, Florida\end{small}
    \end{flushright}
  \end{multicols}
\end{large}
* Cleaned, manipulated, and managed large epidemiological data sets (over 500,000 rows) using statistical tools (e.g., R, SAS/SPSS, Excel), created interactive visualizations, and hosted multiple presentations to report statistical findings on poison exposure within Miami-Dade County.
* **Independently developed and applied statistical models to interpret health data and support decision-making processes for resource allocation.**
* Hosted presentations on Fatal and Non-fatal Drownings, Risk factors, and Prevention strategies through a community outreach program - Foster Grandparents of Miami.

\vspace{5pt}

<!-- EXPERIENCE : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}
      \bf \href{https://www.sevneurology.com/}{Southeast Veterinary Neurology}\\
      Patient Care Coordinator
    \end{flushleft}
    \begin{flushright}
    April 2023 - Jan 2024\\
    \begin{small}Remote\end{small}
    \end{flushright}
  \end{multicols}
\end{large}
* **Independently initiated and managed comprehensive data collection and analysis of team performance metrics, identifying key areas for improvement and optimizing workflows to enhance efficiency.**
* Utilized data visualization tools, such as Excel and R, to effectively present call metric trends and patterns, facilitating better data interpretation and informed decision-making.